{{ $now := now }}
{{ $schedulingTime := .Values.scheduling.time | toDate "2006-01-02T15:04:05Z" }}
{{ if $now.After $schedulingTime }}
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: {{ .Values.resourceGroup.name }}
spec:
  location: {{ .Values.scheduling.location }}
{{ end }}